### ISSUE TITLE
Build correspondence between pixels and points

### ISSUE THREAD

**Issue by KeeganZQJ** [yinyunie/depth_renderer#2]
Hi, thanks for your helpful work. I would like to ask if there is a convenient way of outputing correspondence relationships between pixels on the rendered image and points on the corresponding 3D model. I notice that "visualization/draw_pc_from_depth.py" can generate partial point clouds from specific viewpoints. Is there any function to obtain such "pixel-point" mapping? Look forward to your reply as soon as possible!

**Comment by yinyunie** [comment]
It is actually a back-projection function. Yes, you can find it in `draw_pc_from_depth.py`. What you need are a camera intrinsic matrix and the pixel location on the image.
