### ISSUE TITLE
Background not transparent

### ISSUE THREAD

**Issue by YuQiao0303** [yinyunie/depth_renderer#7]
Hi author! Thank you for this repo!
Using the code, I succesfully get the rendered png images with black backgrounds. What if I want to have transparent background?
I try the following code but it dosen't seem to work. Could you please help?
    if g_background_image_path == 'TRANSPARENT':
        if bpy.app.version < (2, 80, 0):
            bpy.context.scene.render.alpha_mode = 'TRANSPARENT'
            bpy.context.scene.render.image_settings.color_mode = 'RGBA' #
        else:
            bpy.context.scene.render.image_settings.color_mode = 'RGBA'  # blender 2.8
            bpy.context.scene.render.film_transparent = True  # 0 for "SKY"; 1 for "TRANSPARENT

**Comment by YuQiao0303** [comment]
I can't believe after trying for so long and finally propose an issue, and seconds later I found the solution.
It's to set in 'setting.py':
g_rgb_color_mode = 'RGBA' #'RGB'.

**Comment by YuQiao0303** [comment]
I can't believe after trying for so long and finally propose an issue, and seconds later I found the solution.
It's to set in 'setting.py':
g_rgb_color_mode = 'RGBA' #'RGB'.

**Comment by yinyunie** [comment]
haha, thanks a lot for your effort. hope it can help others.
